### PR TITLE
Added Replace function

### PR DESCRIPTION
**Pull request by jabbar86**

### CODE REVIEW

**Comment by jabbar86** [comment]
@marcuspoehls please review it.

**Comment by marcuspoehls** [comment]
@jabbar86 Hey Jabbar, can you please add tests?

**Comment by jabbar86** [comment]
@marcuspoehls on it. Will update you soon

**Comment by jabbar86** [comment]
@marcuspoehls pls check the pr

**Comment by jabbar86** [comment]
@marcuspoehls  any update?

**Comment by marcuspoehls** [comment]
@jabbar86 Hey, can you please add another test ensuring only the first appearance is replaced?

**Comment by jabbar86** [comment]
@marcuspoehls Added Check and let me know.

**Comment by marcuspoehls** [comment]
@jabbar86 Looks good. Thank you Jabbar!

**Pull request merged**
